-- Run this script in the Supabase SQL Editor

-- 1. Create the 'stories' table (Updated to match your Dart code)
CREATE TABLE IF NOT EXISTS public.stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    user_name TEXT, -- Added this field to match your code
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL CHECK (media_type IN ('image', 'video')), -- Renamed from 'type' to 'media_type'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    expire_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now() + interval '24 hours') NOT NULL -- Renamed from 'expires_at' to 'expire_at'
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies

-- Allow anyone to view active stories (not expired)
-- Updated to use 'expire_at' column
CREATE POLICY "View active stories" ON public.stories
    FOR SELECT
    USING (expire_at > timezone('utc'::text, now()));

-- Allow authenticated or anonymous users to insert stories
CREATE POLICY "Enable insert for all users" ON public.stories
    FOR INSERT
    WITH CHECK (true);

-- Allow users to delete their own stories based on user_id 
-- (Assuming trust in client for now as per your implementation)
CREATE POLICY "Enable delete for owners" ON public.stories
    FOR DELETE
    USING (true);
